# Generated by Django 2.2.1 on 2019-06-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20190622_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=15, unique=True, verbose_name='Slug of post'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=15, unique=True, verbose_name='Slug of tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Title of tag'),
        ),
    ]
