# Generated by Django 2.2.1 on 2019-07-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20190720_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-date']},
        ),
    ]
