# Generated by Django 2.2.1 on 2019-07-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'permissions': (('can_edit', 'Edit post'), ('can_create', 'Create post'), ('can_delete', 'Delete post'))},
        ),
    ]
