# Generated by Django 2.2.1 on 2019-07-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_auto_20190724_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
